name: Lighthouse CI
on: [push, pull_request]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build app
        run: npm run build
        
      - name: Start server and run Lighthouse
        run: |
          npm install -g http-server
          http-server build -p 3000 -s &
          SERVER_PID=$!
          sleep 10
          npx @lhci/cli collect --url http://localhost:3000/ --url http://localhost:3000/#/games
          npx @lhci/cli assert --preset lighthouse:no-pwa

          kill $SERVER_PID
